[package]
name = "pipe_cli"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.33.3"
http = "0.2"
regex = "1.5"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
yaml-rust = "0.4.5"
